import requests
import os
import yfinance as yf
from datetime import datetime
import pytz

# --- Configuration ពី GitHub Secrets ---
TOKEN = os.getenv('TELEGRAM_TOKEN')
GROUP_ID = os.getenv('TELEGRAM_ID')
TOPIC_ANALYSIS = os.getenv('TOPIC_ANALYSIS')
TOPIC_ALERTS = os.getenv('TOPIC_ALERTS')

# --- 🎯 ១. កែប្រែទិន្នន័យវិភាគនៅទីនេះរាល់ព្រឹក ---
RESISTANCE_ZONE = "4,465 – 4,540"
SUPPLY_ZONE = "4,420 – 4,460"
MAJOR_DEMAND = "4,000"
SL_PRICE = 4510
TP_LEVELS = "4330 / 4230 / 4000"

# --- 📅 ២. តារាងព័ត៌មានសេដ្ឋកិច្ច (បងអាចដូរព័ត៌មានតាមថ្ងៃនីមួយៗ) ---
NEWS_TABLE = (
    "| ម៉ោង (GMT+7) | ព័ត៌មានសេដ្ឋកិច្ច | កម្រិត | ការរំពឹងទុក |\n"
    "|---|---|---|---|\n"
    "| 🔴 7:30 PM | Initial Jobless Claims | High | 211K |\n"
    "| 🟡 9:00 PM | KC Fed Index | Medium | 10 |\n"
    "| 🔴 10:00 PM | Fed Chair Speech | High | - |"
)

def get_gold_data():
    try:
        gold = yf.Ticker("GC=F")
        data = gold.history(period="2d")
        if data.empty: return None
        curr = data['Close'].iloc[-1]
        prev = data['Close'].iloc[-2]
        high = data['High'].iloc[-1]
        low = data['Low'].iloc[-1]
        pct = ((curr - prev) / prev) * 100
        return {"price": curr, "high": high, "low": low, "pct": pct}
    except: return None

def send_msg(text, topic_id):
    if not topic_id: return
    url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
    payload = {"chat_id": GROUP_ID, "text": text, "parse_mode": "Markdown", "message_thread_id": topic_id}
    requests.post(url, data=payload)

def main():
    data = get_gold_data()
    if not data: return
    
    price = data['price']
    kh_tz = pytz.timezone("Asia/Phnom_Penh")
    now_kh = datetime.now(kh_tz)
    
    current_hour = now_kh.hour
    current_minute = now_kh.minute

    # --- ⏰ លក្ខខណ្ឌផ្ញើ Report តាម Session ---
    is_report_time = False
    session_name = ""

    if current_hour == 8 and current_minute < 15:
        is_report_time = True
        session_name = "🌏 ASIA SESSION"
    elif current_hour == 14 and current_minute < 15:
        is_report_time = True
        session_name = "🇪🇺 LONDON SESSION"
    elif current_hour == 19 and current_minute < 15:
        is_report_time = True
        session_name = "🇺🇸 NEW YORK SESSION"

    if is_report_time:
        report = (
            f"📊 **REPORT: {session_name}**\n"
            f"📅 {now_kh.strftime('%d/%m/%Y')} | ⏰ {now_kh.strftime('%H:%M %p')}\n"
            f"━━━━━━━━━━━━━━━━━━━━\n"
            f"💰 **Price:** `${price:,.2f}` ({data['pct']:+.2f}%)\n"
            f"🏔️ **H/L Today:** `${data['high']:,.2f}` / `${data['low']:,.2f}`\n\n"
            
            f"📰 **HIGH IMPACT NEWS TODAY:**\n"
            f"```\n{NEWS_TABLE}\n```\n"
            
            f"🎯 **INTRADAY ROADMAP**\n"
            f"• Resistance: `${RESISTANCE_ZONE}`\n"
            f"• Supply Zone: `${SUPPLY_ZONE}`\n"
            f"• Major Demand: `${MAJOR_DEMAND}`\n\n"
            
            f"⚡ **SCENARIO:**\n"
            f"• **SL:** `{SL_PRICE}` | **TP:** `{TP_LEVELS}`\n\n"
            f"Generated by **Titanium321 AI** 🚀"
        )
        send_msg(report, TOPIC_ANALYSIS)

    # --- 🚨 Alert តម្លៃ (រត់រាល់ ១៥ នាទី) ---
    if price <= 4375.0:
        send_msg(f"🚨 **GOLD ALERT:** Price hit Support `${price:,.2f}`", TOPIC_ALERTS)
    elif price >= 4465.0:
        send_msg(f"🚨 **GOLD ALERT:** Price hit Resistance `${price:,.2f}`", TOPIC_ALERTS)

if __name__ == "__main__":
    main()
    
