import requests
import os
import yfinance as yf
from datetime import datetime
import pytz

# --- Configuration ពី GitHub Secrets ---
TOKEN = os.getenv('TELEGRAM_TOKEN')
GROUP_ID = os.getenv('TELEGRAM_ID')
TOPIC_ANALYSIS = os.getenv('TOPIC_ANALYSIS')
TOPIC_ALERTS = os.getenv('TOPIC_ALERTS')

# --- 🎯 ២. INTRADAY EXECUTION ROADMAP (បងកែលេខទាំងនេះរាល់ព្រឹក) ---
# Key Zones & Scenarios
RESISTANCE_ZONE = "4,465 – 4,540"
SUPPLY_ZONE = "4,420 – 4,460"
MAJOR_DEMAND = "4,000"

# Target Levels
SL_PRICE = 4510
TP1 = 4330
TP2 = 4230
TP3 = 4000

def get_gold_data():
    try:
        gold = yf.Ticker("GC=F")
        data = gold.history(period="2d")
        if data.empty: return None
        curr = data['Close'].iloc[-1]
        prev = data['Close'].iloc[-2]
        high = data['High'].iloc[-1]
        low = data['Low'].iloc[-1]
        pct = ((curr - prev) / prev) * 100
        return {"price": curr, "high": high, "low": low, "pct": pct}
    except: return None

def send_msg(text, topic_id):
    if not topic_id: return
    url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
    payload = {"chat_id": GROUP_ID, "text": text, "parse_mode": "Markdown", "message_thread_id": topic_id}
    requests.post(url, data=payload)

def main():
    data = get_gold_data()
    if not data: return
    
    price = data['price']
    kh_time = datetime.now(pytz.timezone("Asia/Phnom_Penh")).strftime('%A ទី %d %មីនា %Y')
    exact_time = datetime.now(pytz.timezone("Asia/Phnom_Penh")).strftime('%H:%M %p')

    # --- រៀបចំអត្ថបទតាម Style បងចង់បាន ---
    report = (
        f"📊 **របាយការណ៍វិភាគមាសប្រចាំថ្ងៃ (XAU/USD)**\n"
        f"*{kh_time} | {exact_time}*\n"
        f"━━━━━━━━━━━━━━━━━━━━\n"
        f"• **Current Price:** `${price:,.2f}` (Real-time)\n"
        f"• **Daily % Change:** `{data['pct']:+.2f}%`\n"
        f"• **Today’s High/Low:** `${data['high']:,.2f}` / `${data['low']:,.2f}`\n\n"
        
        f"🌍 **១. ស្ថានភាព MACO & ព័ត៌មាន**\n"
        f"📊 **និន្នាការ:** {'📈 BULLISH' if data['pct'] > 0 else '📉 BEARISH'}\n"
        f"ទីផ្សារកំពុងស្ថិតក្នុងដំណាក់កាលប្រែប្រួលខ្លាំង។ ត្រូវតាមដានព័ត៌មាន High Impact យប់នេះ និងស្ថានភាព Geopolitics ដែលអាចរុញ DXY ឱ្យហក់ឡើង។\n\n"
        
        f"🎯 **២. INTRADAY EXECUTION ROADMAP**\n"
        f"🗺️ **Key Zones:**\n"
        f"• Key Resistance: `${RESISTANCE_ZONE}`\n"
        f"• Supply (Wait SELL): `${SUPPLY_ZONE}`\n"
        f"• Major Demand: `${MAJOR_DEMAND}`\n\n"
        
        f"⚡ **Trade Scenario A (SELL)**\n"
        f"• Entry: `${SUPPLY_ZONE}`\n"
        f"• **SL:** `{SL_PRICE}` | **TP:** `{TP1} / {TP2} / {TP3}`\n"
        f"• RR: ≈ 1:3.2 ✅\n\n"
        
        f"⚠️ **៣. ការគ្រប់គ្រងហានិភ័យ (Risk Management)**\n"
        f"• ផ្ដោតលើវគ្គជួញដូរ New York សម្រាប់ទំហំជួញដូរខ្ពស់។\n"
        f"• Risk per Trade: រក្សាត្រឹម **1%** ប៉ុណ្ណោះក្នុងស្ថានភាពនេះ។\n\n"
        f"Generated by **Titanium321 AI** 🚀\n"
        f"📌 *Educational Purpose Only*"
    )

    send_msg(report, TOPIC_ANALYSIS)

if __name__ == "__main__":
    main()
    
