name: Gold Auto Bot

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests pytz
      - name: Run bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          FINNHUB_TOKEN: ${{ secrets.FINNHUB_TOKEN }}
          TELEGRAM_ID: ${{ secrets.TELEGRAM_ID }}
          TOPIC_ANALYSIS: ${{ vars.TOPIC_ANALYSIS }}
          TOPIC_ALERTS: ${{ vars.TOPIC_ALERTS }}
        run: python bot.py
        
